name: "Validate HTML"

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
